### ISSUE TITLE
Reason to use pragma once and inclusion guarding marco together?

### ISSUE THREAD

**Issue by yungyuc** [abt8601/diffusion-maps#1]
In https://github.com/abt8601/diffusion-maps/blob/d48156b843363e43b7e9b1cf9f4f7a57e3541bef/include/diffusion_maps/eig_solver.hpp#L2 I see you use both `#pragma once` and the inclusion guarding macro `DIFFUSION_MAPS_EIG_SOLVER_HPP` together and wonder why?

I like your use of both Google test and pytest in CI.  IIUC, the pytest includes only a dummy test.  I would be interested in how you would like to wrap for your Python API.  Let me know if you need any discussions or help.

**Comment by abt8601** [comment]
I guess using `#pragma once` and `#include` guards together is from a habit I picked up several years ago. I learnt somewhere that using `#pragma once` could decrease compilation time, so I started to use it (although the gain should be marginal for a project of this scale). At the same time, `#pragma once` is non-standard, so I use a regular `#include` guard as a backup. I guess I'll stick with regular `#include` guards in the future.

The Python API will pretty much be what's stated in the proposal with some minor changes. Pytest will be used to test the whole algorithm on simple datasets to see if the result makes sense – or, at the very least, doesn't return an array of NaNs. They should be pushed to the repository within a few days.

**Comment by yungyuc** [comment]
> I guess using `#pragma once` and `#include` guards together is from a habit I picked up several years ago. I learnt somewhere that using `#pragma once` could decrease compilation time, so I started to use it (although the gain should be marginal for a project of this scale). At the same time, `#pragma once` is non-standard, so I use a regular `#include` guard as a backup. I guess I'll stick with regular `#include` guards in the future.

Either is OK.  Having said that, I have not encountered a modern compiler that does not make `#pragma once` work perfectly for a while.

> 
> The Python API will pretty much be what's stated in the proposal with some minor changes. Pytest will be used to test the whole algorithm on simple datasets to see if the result makes sense – or, at the very least, doesn't return an array of NaNs. They should be pushed to the repository within a few days.

I look forward to it and will come back to take a look when I have time.  Feel free to tag me if you want me to see anything.
